In [ ]:
import numpy as np

# DataAnalytics class - encapsulates all NumPy operations
class DataAnalytics:
    # Class-level private variable to store toolkit name
    __name_toolkit = "Numpy analyst"

    # Constructor - initializes the array as None
    def __init__(self):
        self.__array = None  # Private attribute to store the NumPy array

    # Property decorator to create getter for the private array
    @property
    def array(self):
        return self.__array

    # Setter for the private array - converts input to NumPy array
    @array.setter
    def array(self,value):
        self.__array = np.array(value)

    # Static method - can be called without creating an object
    @staticmethod
    def display():
        print("Welcome to the NumPY analyst!")

    # Class method - alternative constructor to create object from a range
    @classmethod
    def create_from_range(cls,start,end,step = 1):
        obj = cls()  # Creates a new DataAnalytics object
        obj._DataAnalytics__array = np.arange(start,end,step)
        return obj

    # Private method to check if array has been created
    def __check(self):
        if self.__array is None:
            print("\nNo array found! Please create an array first.")
            return False
        return True

    # Method to create 1D, 2D, or 3D arrays based on user input
    def create_array(self):
        print("\nSelect the type of array to create:")
        print("\n1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        user = input("\nEnter your choice : ")

        if user == "1":
            # Creating a 1D array from user input
            try:
                ar = input("\nEnter elements separated by space : ").split()
                # List comprehension to convert strings to integers
                self.__array = np.array([int(x) for x in ar])

            except Exception as e:
                print(e)

        elif user == "2":
            # Creating a 2D array using reshape
            try:
                rows = int(input("Enter the number of rows : "))
                columns = int(input("Enter the number of columns : "))

                arr = input(f"Enter {rows * columns} elemnts for the array separated by space : ").split()
                # Reshape 1D input into 2D array with given rows and columns
                self.__array = np.array([int(x) for x in arr]).reshape(rows,columns)

            except Exception as e:
                print(e)

        elif user == "3":
            # Creating a 3D array using reshape with depth, rows, and columns
            try:
                dept = int(input("\nEnter the depth (number of 2D matrices) : "))
                rows = int(input("Enter the number of rows : "))
                columns = int(input("Enter the number of columns : "))

                arr = input(f"Enter {dept * rows * columns} elemnts for the array separated by space : ").split()
                # Reshape into 3D array
                self.__array = np.array([int(x) for x in arr]).reshape(dept,rows,columns)

            except Exception as e:
                print(e)   

        else :
            print("Invaild choice.")
            return

        print("\nArray created successfully:")
        print(self.__array)

    # Method for indexing and slicing operations on the array
    def sli(self):

        print("\nChoose an operation:")
        print('\n1. Indexing')
        print("2. Slicing")
        print("3. Go Back")
        user = input("\nEnter your choice : ")

        if user == "1":
            # Indexing - access a single element by its position
            try:
                if self.__array.ndim == 1:
                    # 1D array - needs one index
                    ind = int(input("Enter your index number : "))
                    print(f"Element at index {ind} : {self.__array[ind]}")

                elif self.__array.ndim == 2:
                    # 2D array - needs row and column index
                    row = int(input("Enter the number of rows : "))
                    col = int(input("Enter the number of columns : "))
                    print(f"\nElement at ({row}, {col}): {self.__array[row, col]}")

                elif self.__array.ndim == 3:
                    # 3D array - needs depth, row, and column index
                    dep = int(input("Enter the depth index: "))
                    row = int(input("Enter the row index: "))
                    col = int(input("Enter the column index: "))
                    print(f"\nElement at ({dep}, {row}, {col}): {self.__array[dep, row, col]}")

            except Exception as e:
                print(e)

        elif user == "2":
            # Slicing - access a range of elements using start:end
            try:
                if self.__array.ndim == 1:
                    # 1D slicing - single range
                    s = input("Enter the slice range (start:end): ").split(":")
                    start = int(s[0]) if s[0] else None
                    end = int(s[1]) if s[1] else None
                    print(f"\nSliced Array:\n{self.__array[start:end]}")
                else:
                    # 2D/3D slicing - row range and column range
                    r = input("Enter the row range (start:end): ").split(":")
                    c = input("Enter the column range (start:end): ").split(":")
                    r_start = int(r[0]) if r[0] else None
                    r_end = int(r[1]) if r[1] else None
                    c_start = int(c[0]) if c[0] else None
                    c_end = int(c[1]) if c[1] else None
                    print(f"\nSliced Array:\n{self.__array[r_start:r_end, c_start:c_end]}")

            except Exception as e:
                print(e)

        elif user == "3":
            print("Backed!!")

        else :
            print("Invalid input!!")

    # Method for element-wise mathematical operations
    def math(self):
        if not self.__check():
            return

        print("\nChoose a mathematical operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Dot Product (2D only)")
        print("6. Matrix Multiplication (2D only)")

        choice = input("Enter your choice: ")

        try:
            if choice in ["1", "2", "3", "4"]:
                total = self.__array.size
                elements = input(f"Enter the same-size array elements ({total} elements separated by space): ").split()
                second = np.array([int(x) for x in elements]).reshape(self.__array.shape)

                print(f"\nOriginal Array:\n{self.__array}")
                print(f"\nSecond Array:\n{second}")

                if choice == "1":
                    print(f"\nResult of Addition:\n{self.__array + second}")
                elif choice == "2":
                    print(f"\nResult of Subtraction:\n{self.__array - second}")
                elif choice == "3":
                    print(f"\nResult of Multiplication:\n{self.__array * second}")
                elif choice == "4":
                    print(f"\nResult of Division:\n{self.__array / second}")

            elif choice == "5":
                if self.__array.ndim != 2:
                    print("Dot product is only for 2D arrays.")
                    return
                total = self.__array.size
                elements = input(f"Enter {total} elements for second array: ").split()
                second = np.array([int(x) for x in elements]).reshape(self.__array.shape)

                print(f"\nOriginal Array:\n{self.__array}")
                print(f"\nSecond Array:\n{second}")
                print(f"\nDot Product Result:\n{np.dot(self.__array, second.T)}")

            elif choice == "6":
                if self.__array.ndim != 2:
                    print("Matrix Multiplication only for 2D array.")
                    return

                rows1, cols1 = self.__array.shape
                rows2 = int(input(f"Enter rows for second matrix (should be {cols1}): "))
                cols2 = int(input("Enter columns for second matrix: "))

                if rows2 != cols1:
                    print("Cannot multiply! Columns of first must equal rows of second.")
                    return

                total = rows2 * cols2
                elements = input(f"Enter {total} elements for second matrix: ").split()
                second = np.array([int(x) for x in elements]).reshape(rows2, cols2)

                print(f"\nOriginal Array:\n{self.__array}")
                print(f"\nSecond Array:\n{second}")
                print(f"\nMatrix Multiplication Result:\n{self.__array @ second}")

            else:
                print("Invalid choice.")

        except Exception as e:
            print(e)

    # Method to combine or split arrays
    def com_slp(self):
        if not self.__check():
            return

        print("\nChoose an option:")
        print("1. Combine Arrays")
        print("2. Split Array")
        choice = input("Enter your choice: ")

        try:
            if choice == "1":
                # Combine - concatenate or vertical stack
                total = self.__array.size
                elements = input(f"Enter the elements of another array to combine ({total} elements separated by space): ").split()
                second = np.array([int(x) for x in elements]).reshape(self.__array.shape)

                print(f"\nOriginal Array:\n{self.__array}")
                print(f"\nSecond Array:\n{second}")

                if self.__array.ndim == 1:
                    # 1D - use concatenate to join arrays
                    print(f"\nCombined Array (Concatenated):\n{np.concatenate([self.__array, second])}")
                else:
                    # 2D/3D - use vstack to stack vertically
                    print(f"\nCombined Array (Vertical Stack):\n{np.vstack([self.__array, second])}")

            elif choice == "2":
                # Split array into n equal parts
                n = int(input("Enter the number of splits: "))
                if self.__array.ndim == 1:
                    parts = np.array_split(self.__array, n)
                else:
                    # axis=0 means split along rows
                    parts = np.array_split(self.__array, n, axis=0)

                print(f"\nArray split into {n} parts:")
                for i, part in enumerate(parts):
                    print(f"  Part {i + 1}: {part}")

            else:
                print("Invalid choice.")

        except Exception as e:
            print(e)

    # Method for searching, sorting, and filtering the array
    def sea_sort(self):
            if not self.__check():
                return
            try:
                print("\nChoose an option:")
                print("1. Search a value")
                print("2. Sort the array")
                print("3. Filter values")
                choice = input("Enter your choice: ")
        
                if choice == "1":
                    # Search - find index of a value using np.where
                    value = int(input("Enter the value to search: "))
                    result = np.where(self.__array == value)
                    if result[0].size > 0:
                        print(f"\nValue {value} found at index/indices: {result}")
                    else:
                        print(f"\nValue {value} not found in the array.")
        
                elif choice == "2":
                    # Sort - returns sorted copy of array
                    print(f"\nOriginal Array:\n{self.__array}")
                    print(f"\nSorted Array:\n{np.sort(self.__array)}")
                    if self.__array.ndim > 1:
                        print("(Sorting applied row-wise.)")
        
                elif choice == "3":
                    # Filter - use boolean indexing to filter elements
                    print("\nChoose a filter condition:")
                    print("1. Greater than a value")
                    print("2. Less than a value")
                    print("3. Equal to a value")
                    print("4. Between two values")
                    f_choice = input("Enter your choice: ")
        
                    if f_choice == "1":
                        val = int(input("Enter the value: "))
                        print(f"\nElements greater than {val}: {self.__array[self.__array > val]}")
                    elif f_choice == "2":
                        val = int(input("Enter the value: "))
                        print(f"\nElements less than {val}: {self.__array[self.__array < val]}")
                    elif f_choice == "3":
                        val = int(input("Enter the value: "))
                        print(f"\nElements equal to {val}: {self.__array[self.__array == val]}")
                    elif f_choice == "4":
                        # Filter between two values using & (AND) operator
                        low = int(input("Enter the lower bound: "))
                        high = int(input("Enter the upper bound: "))
                        print(f"\nElements between {low} and {high}: {self.__array[(self.__array >= low) & (self.__array <= high)]}")
                    else:
                        print("Invalid choice.")
        
                else:
                    print("Invalid choice.")

            except Exception as e:
                print(e)
        
    # Method for computing aggregate and statistical operations
    def ag_stat(self):
            if not self.__check():
                return
    
            print(self.__array)
    
            print("\nChoose an aggregate/statistical operation:")
            print("1. Sum")
            print("2. Mean")
            print("3. Median")
            print("4. Standard Deviation")
            print("5. Variance")
            choice = input("Enter your choice: ")
            try:
                if choice == "1":
                    print(f"\nSum: {np.sum(self.__array)}")
                elif choice == "2":
                    print(f"\nMean: {np.mean(self.__array)}")
                elif choice == "3":
                    print(f"\nMedian: {np.median(self.__array)}")
                elif choice == "4":
                    print(f"\nStandard Deviation: {np.std(self.__array)}")
                elif choice == "5":
                    print(f"\nVariance: {np.var(self.__array)}")
            except Exception as e:
                print(e)

# Main function - menu-driven user interface
def main():

    analyst = DataAnalytics()

    print("\nWelcome to the NumPy analyst!")
    print("=" * 40)
    
    while True:
        # Main menu options
        print("\nChoose an option:")
        print("1. Create a Numpy Array")
        print("2. Perform Mathematical Operations")
        print("3. Combine or Split Arrays")
        print("4. Search, Sort, or Filter Arrays")
        print("5. Compute Aggregates and Statistics")
        print("6. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
    
            # Sub-menu for array creation and indexing/slicing
            print("1. Create a new array")
            print("2. Indexing and Slicing")
            sub = input("Enter your choice: ")

            if sub == "1":
                analyst.create_array()

            elif sub == "2":
                analyst.sli()

            else :
                print("Invalid Choice!")

        elif choice == "2":
            analyst.math()

        elif choice == "3":
            analyst.com_slp()

        elif choice == "4":
            analyst.sea_sort()

        elif choice == "5":
            analyst.ag_stat()

        elif choice == "6":
            print("\nThank you for using the NumPy Analyzer! Goodbye !")
            break

        else:
            print("Invalid choice.")


if __name__ == "__main__" :
    main()


Welcome to the NumPy analyst!

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1


1. Create a new array
2. Indexing and Slicing


Enter your choice:  1



Select the type of array to create:

1. 1D Array
2. 2D Array
3. 3D Array



Enter your choice :  2
Enter the number of rows :  2
Enter the number of columns :  3
Enter 6 elemnts for the array separated by space :  20 30 40 50 60 70



Array created successfully:
[[20 30 40]
 [50 60 70]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1


1. Create a new array
2. Indexing and Slicing


Enter your choice:  2



Choose an operation:

1. Indexing
2. Slicing
3. Go Back



Enter your choice :  1
Enter the number of rows :  0
Enter the number of columns :  2



Element at (0, 2): 40

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1


1. Create a new array
2. Indexing and Slicing


Enter your choice:  2



Choose an operation:

1. Indexing
2. Slicing
3. Go Back



Enter your choice :  2
Enter the row range (start:end):  0:2
Enter the column range (start:end):  0:1



Sliced Array:
[[20]
 [50]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  1
Enter the same-size array elements (6 elements separated by space):  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2 3]
 [4 5 6]]

Result of Addition:
[[21 32 43]
 [54 65 76]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  2
Enter the same-size array elements (6 elements separated by space):  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2 3]
 [4 5 6]]

Result of Subtraction:
[[19 28 37]
 [46 55 64]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  3
Enter the same-size array elements (6 elements separated by space):  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2 3]
 [4 5 6]]

Result of Multiplication:
[[ 20  60 120]
 [200 300 420]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  4
Enter the same-size array elements (6 elements separated by space):  2 2 2 2 2 2



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[2 2 2]
 [2 2 2]]

Result of Division:
[[10. 15. 20.]
 [25. 30. 35.]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  5
Enter 6 elements for second array:  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2 3]
 [4 5 6]]

Dot Product Result:
[[200 470]
 [380 920]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
6. Matrix Multiplication (2D only)


Enter your choice:  6
Enter rows for second matrix (should be 3):  3
Enter columns for second matrix:  2
Enter 6 elements for second matrix:  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2]
 [3 4]
 [5 6]]

Matrix Multiplication Result:
[[310 400]
 [580 760]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  3



Choose an option:
1. Combine Arrays
2. Split Array


Enter your choice:  1
Enter the elements of another array to combine (6 elements separated by space):  1 2 3 4 5 6



Original Array:
[[20 30 40]
 [50 60 70]]

Second Array:
[[1 2 3]
 [4 5 6]]

Combined Array (Vertical Stack):
[[20 30 40]
 [50 60 70]
 [ 1  2  3]
 [ 4  5  6]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  3



Choose an option:
1. Combine Arrays
2. Split Array


Enter your choice:  2
Enter the number of splits:  2



Array split into 2 parts:
  Part 1: [[20 30 40]]
  Part 2: [[50 60 70]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  4



Choose an option:
1. Search a value
2. Sort the array
3. Filter values


Enter your choice:  1
Enter the value to search:  20



Value 20 found at index/indices: (array([0]), array([0]))

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  4



Choose an option:
1. Search a value
2. Sort the array
3. Filter values


Enter your choice:  2



Original Array:
[[20 30 40]
 [50 60 70]]

Sorted Array:
[[20 30 40]
 [50 60 70]]
(Sorting applied row-wise.)

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
